language: python
python:
    - "2.7"
install: pip install --use-mirrors . && pip install -r requirements.txt
script: unit2 discover
notifications:
    irc:
        channels: 
            - "irc.mozilla.org#services-dev"
        on_success: change
